export default {
    'inList': [
        {name: 'gongzi', title: '工资'},
        {name: 'jianzhi', title: '兼职'},
        {name: 'qianbao', title: '生活费'},
        {name: 'hongbao', title: '红包'},
        {name: 'jiangjin', title: '奖金'},
        {name: 'baoxiao', title: '报销'},
        {name: 'touzi', title: '投资'},
        {name: 'jiekuan', title: '借款'},
        {name: 'tuikuan', title: '退款'},
        {name: 'shezhi', title: '自定义'}
    ],
    "outList": [
        {name: 'canyin', title: '餐饮'},
        {name: 'shuiguo', title: '水果'},
        {name: 'jiaotong', title: '零食'},
        {name: 'maicai', title: '买菜'},
        {name: 'tongxun', title: '通讯'},
        {name: 'shenghuo', title: '生活用品'},
        {name: 'fushi', title: '服饰'},
        {name: 'meirong', title: '美容'},
        {name: 'yule', title: '娱乐'},
        {name: 'jianshen', title: '健身'},
        {name: 'baoxian', title: '保险'},
        {name: 'yiyuan', title: '医疗'},
        {name: 'touzi', title: '投资'},
        {name: 'xuexi', title: '学习'},
        {name: 'jiaju', title: '家居'},
        {name: 'zhufang', title: '住房'},
        {name: 'shuidian', title: '水电费'},
        {name: 'weixiu', title: '维修'},
        {name: 'tingche', title: '停车'},
        {name: 'jiayou', title: '加油'},
        {name: 'lufei', title: '过路费'},
        {name: 'songli', title: '送礼'},
        {name: 'haizi', title: '孩子'},
        {name: 'huankuan', title: '还款'},
        {name: 'shuma', title: '数码'},
        {name: 'apple', title: 'app'},
        {name: 'shezhi', title: '自定义'}
    ],
};